version: '2'

services:
  postgres:
    image: postgres:latest
    env_file: bin/dev.env
  api:
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - postgres
    command: ["./bin/wait-for-it.sh", "aerospike:3030", "--", "npm", "start"]
    env_file: bin/dev.env
    ports:
      - "3030:3030"
      - "9229:9229"
